# Generated by Django 4.0.4 on 2022-06-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='printcipal',
            new_name='principal',
        ),
    ]
