# Generated by Django 4.0.4 on 2022-05-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_rename_profile_pic_userprofileinfo_profile_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pics',
            new_name='profile_pic',
        ),
    ]
